version: '3.8'

services:
  web:
    build: .
    command: python main.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_UB_NAME=hello_flask

volumes:
  postgres_data: