# Generated by Django 3.1.1 on 2022-08-31 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20220831_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_title',
            new_name='title',
        ),
    ]
