version: '3.8'

services:
  web:
    build: .
    command: python main.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    container_name: library_db
    restart: always
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=library
      - POSTGRES_PASSWORD=library
      - POSTGRES_DB_NAME=library
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://library:library@db:5432/library?sslmode=disable
    depends_on:
      - db

volumes:
  postgres_data: