# Generated by Django 3.1.1 on 2022-08-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0002_product_display_on_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(null=True, to='categories.Category'),
        ),
    ]
